title: Pim Kamphuis
description: Looking for me? I am probably somewhere up in the cloud...
baseurl: /
url: https://pimkamphuis.com

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
newtab: true
lowercase: false

title: Pim Kamphuis
tagline: Looking for me? I am probably somewhere up in the cloud.

url: pimkamphuis.com
author: Pim Kamphuis

google_site_verification: 