title: Pim Kamphuis
description: Looking for me? I am probably somewhere up in the cloud...

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: "G-0HCTRFNY49"

sass:
  sourcemap: never
  
lowercase: false

title: Pim Kamphuis
tagline: Looking for me? I am probably somewhere up in the cloud.

url: https://pimkamphuis.com
author: Pim Kamphuis

newtab: true